<?php

namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20171229135407 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE agents DROP CONSTRAINT FK_9596AB6EB03A8386');
        $this->addSql('ALTER TABLE agents DROP CONSTRAINT FK_9596AB6E99049ECE');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT FK_9596AB6EB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT FK_9596AB6E99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_type DROP CONSTRAINT FK_2145EDCAB03A8386');
        $this->addSql('ALTER TABLE agent_type DROP CONSTRAINT FK_2145EDCA99049ECE');
        $this->addSql('ALTER TABLE agent_type ADD CONSTRAINT FK_2145EDCAB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_type ADD CONSTRAINT FK_2145EDCA99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.attributes DROP CONSTRAINT FK_344DC391B03A8386');
        $this->addSql('ALTER TABLE flora.attributes DROP CONSTRAINT FK_344DC39199049ECE');
        $this->addSql('ALTER TABLE flora.attributes ADD CONSTRAINT FK_344DC391B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.attributes ADD CONSTRAINT FK_344DC39199049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT FK_A702D713B03A8386');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT FK_A702D71399049ECE');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT FK_A702D713B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT FK_A702D71399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT FK_F6F7DDB3B03A8386');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT FK_F6F7DDB399049ECE');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT FK_F6F7DDB3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT FK_F6F7DDB399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab DROP CONSTRAINT FK_95FEFE0DB03A8386');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab DROP CONSTRAINT FK_95FEFE0D99049ECE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab ADD CONSTRAINT FK_95FEFE0DB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab ADD CONSTRAINT FK_95FEFE0D99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT FK_461073BEB03A8386');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT FK_461073BE99049ECE');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT FK_461073BEB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT FK_461073BE99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images DROP CONSTRAINT FK_E8D0BC6FB03A8386');
        $this->addSql('ALTER TABLE cumulus.cumulus_images DROP CONSTRAINT FK_E8D0BC6F99049ECE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images ADD CONSTRAINT FK_E8D0BC6FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images ADD CONSTRAINT FK_E8D0BC6F99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.events DROP CONSTRAINT FK_DB624B93B03A8386');
        $this->addSql('ALTER TABLE images.events DROP CONSTRAINT FK_DB624B9399049ECE');
        $this->addSql('ALTER TABLE images.events ADD CONSTRAINT FK_DB624B93B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.events ADD CONSTRAINT FK_DB624B9399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.feature_vocab DROP CONSTRAINT FK_F5ABA083B03A8386');
        $this->addSql('ALTER TABLE vocab.feature_vocab DROP CONSTRAINT FK_F5ABA08399049ECE');
        $this->addSql('ALTER TABLE vocab.feature_vocab ADD CONSTRAINT FK_F5ABA083B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.feature_vocab ADD CONSTRAINT FK_F5ABA08399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C7B03A8386');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C799049ECE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C7B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C799049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B3B03A8386');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B399049ECE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT FK_15E807F3B03A8386');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT FK_15E807F399049ECE');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT FK_15E807F3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT FK_15E807F399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT FK_4E03B854B03A8386');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT FK_4E03B85499049ECE');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT FK_4E03B854B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT FK_4E03B85499049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.license_vocab DROP CONSTRAINT FK_B8C10401B03A8386');
        $this->addSql('ALTER TABLE vocab.license_vocab DROP CONSTRAINT FK_B8C1040199049ECE');
        $this->addSql('ALTER TABLE vocab.license_vocab ADD CONSTRAINT FK_B8C10401B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.license_vocab ADD CONSTRAINT FK_B8C1040199049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.locations DROP CONSTRAINT FK_A3A90F27B03A8386');
        $this->addSql('ALTER TABLE images.locations DROP CONSTRAINT FK_A3A90F2799049ECE');
        $this->addSql('ALTER TABLE images.locations ADD CONSTRAINT FK_A3A90F27B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.locations ADD CONSTRAINT FK_A3A90F2799049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT FK_FD5D642BB03A8386');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT FK_FD5D642B99049ECE');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT FK_FD5D642BB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT FK_FD5D642B99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab DROP CONSTRAINT FK_3B646613B03A8386');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab DROP CONSTRAINT FK_3B64661399049ECE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab ADD CONSTRAINT FK_3B646613B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab ADD CONSTRAINT FK_3B64661399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab DROP CONSTRAINT FK_6D68CADEB03A8386');
        $this->addSql('ALTER TABLE vocab.subtype_vocab DROP CONSTRAINT FK_6D68CADE99049ECE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab ADD CONSTRAINT FK_6D68CADEB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab ADD CONSTRAINT FK_6D68CADE99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.variant_vocab DROP CONSTRAINT FK_BC7F35D7B03A8386');
        $this->addSql('ALTER TABLE vocab.variant_vocab DROP CONSTRAINT FK_BC7F35D799049ECE');
        $this->addSql('ALTER TABLE vocab.variant_vocab ADD CONSTRAINT FK_BC7F35D7B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.variant_vocab ADD CONSTRAINT FK_BC7F35D799049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT FK_7255A4E3B03A8386');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT FK_7255A4E399049ECE');
        $this->addSql('ALTER TABLE flora.links ADD query VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE flora.links ALTER path DROP NOT NULL');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT FK_7255A4E3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT FK_7255A4E399049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT FK_51E44CBBB03A8386');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT FK_51E44CBB99049ECE');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT FK_51E44CBBB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT FK_51E44CBB99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab DROP CONSTRAINT FK_9B076CD1B03A8386');
        $this->addSql('ALTER TABLE vocab.name_type_vocab DROP CONSTRAINT FK_9B076CD199049ECE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab ADD CONSTRAINT FK_9B076CD1B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab ADD CONSTRAINT FK_9B076CD199049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab DROP CONSTRAINT FK_FF443D0AB03A8386');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab DROP CONSTRAINT FK_FF443D0A99049ECE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab ADD CONSTRAINT FK_FF443D0AB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab ADD CONSTRAINT FK_FF443D0A99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT FK_90187B9BB03A8386');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT FK_90187B9B99049ECE');
        $this->addSql('ALTER TABLE organization_agents ADD start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE organization_agents ADD end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT FK_90187B9BB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT FK_90187B9B99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "references" DROP CONSTRAINT FK_9F1E2D9CB03A8386');
        $this->addSql('ALTER TABLE "references" DROP CONSTRAINT FK_9F1E2D9C99049ECE');
        $this->addSql('ALTER TABLE "references" ADD CONSTRAINT FK_9F1E2D9CB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "references" ADD CONSTRAINT FK_9F1E2D9C99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.regions DROP CONSTRAINT FK_254516DDB03A8386');
        $this->addSql('ALTER TABLE flora.regions DROP CONSTRAINT FK_254516DD99049ECE');
        $this->addSql('ALTER TABLE flora.regions ADD depth INT DEFAULT NULL');
        $this->addSql('ALTER TABLE flora.regions ADD CONSTRAINT FK_254516DDB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.regions ADD CONSTRAINT FK_254516DD99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492B03A8386');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A649299049ECE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A649299049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT FK_CC70FD9B03A8386');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT FK_CC70FD999049ECE');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT FK_CC70FD9B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT FK_CC70FD999049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab DROP CONSTRAINT FK_58767F5EB03A8386');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab DROP CONSTRAINT FK_58767F5E99049ECE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab ADD CONSTRAINT FK_58767F5EB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab ADD CONSTRAINT FK_58767F5E99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT FK_A242BC35B03A8386');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT FK_A242BC3599049ECE');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT FK_A242BC35B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT FK_A242BC3599049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT FK_4E6A844BB03A8386');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT FK_4E6A844B99049ECE');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER node_number DROP NOT NULL');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER highest_descendant_node_number DROP NOT NULL');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER depth TYPE INT');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER depth DROP DEFAULT');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER depth DROP NOT NULL');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT FK_4E6A844BB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT FK_4E6A844B99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items DROP CONSTRAINT FK_86F092AB03A8386');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items DROP CONSTRAINT FK_86F092A99049ECE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items ADD CONSTRAINT FK_86F092AB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items ADD CONSTRAINT FK_86F092A99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab DROP CONSTRAINT FK_34242DE2B03A8386');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab DROP CONSTRAINT FK_34242DE299049ECE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab ADD CONSTRAINT FK_34242DE2B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab ADD CONSTRAINT FK_34242DE299049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93ECB03A8386');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93EC99049ECE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93ECB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93EC99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatment_versions DROP CONSTRAINT FK_8A89D541B03A8386');
        $this->addSql('ALTER TABLE flora.treatment_versions DROP CONSTRAINT FK_8A89D54199049ECE');
        $this->addSql('ALTER TABLE flora.treatment_versions ADD CONSTRAINT FK_8A89D541B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatment_versions ADD CONSTRAINT FK_8A89D54199049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT FK_8807A55FB03A8386');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT FK_8807A55F99049ECE');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT FK_8807A55FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT FK_8807A55F99049ECE FOREIGN KEY (modified_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE agent_type DROP CONSTRAINT fk_2145edcab03a8386');
        $this->addSql('ALTER TABLE agent_type DROP CONSTRAINT fk_2145edca99049ece');
        $this->addSql('ALTER TABLE agent_type ADD CONSTRAINT fk_2145edcab03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_type ADD CONSTRAINT fk_2145edca99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT fk_a702d713b03a8386');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT fk_a702d71399049ece');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT fk_a702d713b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT fk_a702d71399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT fk_f6f7ddb3b03a8386');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT fk_f6f7ddb399049ece');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT fk_f6f7ddb3b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT fk_f6f7ddb399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT fk_461073beb03a8386');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT fk_461073be99049ece');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT fk_461073beb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT fk_461073be99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images DROP CONSTRAINT fk_e8d0bc6fb03a8386');
        $this->addSql('ALTER TABLE cumulus.cumulus_images DROP CONSTRAINT fk_e8d0bc6f99049ece');
        $this->addSql('ALTER TABLE cumulus.cumulus_images ADD CONSTRAINT fk_e8d0bc6fb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images ADD CONSTRAINT fk_e8d0bc6f99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT fk_553d98c7b03a8386');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT fk_553d98c799049ece');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT fk_553d98c7b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT fk_553d98c799049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT fk_15e807f3b03a8386');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT fk_15e807f399049ece');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT fk_15e807f3b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT fk_15e807f399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT fk_68faa2b3b03a8386');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT fk_68faa2b399049ece');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT fk_68faa2b3b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT fk_68faa2b399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.feature_vocab DROP CONSTRAINT fk_f5aba083b03a8386');
        $this->addSql('ALTER TABLE vocab.feature_vocab DROP CONSTRAINT fk_f5aba08399049ece');
        $this->addSql('ALTER TABLE vocab.feature_vocab ADD CONSTRAINT fk_f5aba083b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.feature_vocab ADD CONSTRAINT fk_f5aba08399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT fk_4e03b854b03a8386');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT fk_4e03b85499049ece');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT fk_4e03b854b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT fk_4e03b85499049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.license_vocab DROP CONSTRAINT fk_b8c10401b03a8386');
        $this->addSql('ALTER TABLE vocab.license_vocab DROP CONSTRAINT fk_b8c1040199049ece');
        $this->addSql('ALTER TABLE vocab.license_vocab ADD CONSTRAINT fk_b8c10401b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.license_vocab ADD CONSTRAINT fk_b8c1040199049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.locations DROP CONSTRAINT fk_a3a90f27b03a8386');
        $this->addSql('ALTER TABLE images.locations DROP CONSTRAINT fk_a3a90f2799049ece');
        $this->addSql('ALTER TABLE images.locations ADD CONSTRAINT fk_a3a90f27b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.locations ADD CONSTRAINT fk_a3a90f2799049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.events DROP CONSTRAINT fk_db624b93b03a8386');
        $this->addSql('ALTER TABLE images.events DROP CONSTRAINT fk_db624b9399049ece');
        $this->addSql('ALTER TABLE images.events ADD CONSTRAINT fk_db624b93b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.events ADD CONSTRAINT fk_db624b9399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT fk_fd5d642bb03a8386');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT fk_fd5d642b99049ece');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT fk_fd5d642bb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT fk_fd5d642b99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab DROP CONSTRAINT fk_3b646613b03a8386');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab DROP CONSTRAINT fk_3b64661399049ece');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab ADD CONSTRAINT fk_3b646613b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab ADD CONSTRAINT fk_3b64661399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab DROP CONSTRAINT fk_6d68cadeb03a8386');
        $this->addSql('ALTER TABLE vocab.subtype_vocab DROP CONSTRAINT fk_6d68cade99049ece');
        $this->addSql('ALTER TABLE vocab.subtype_vocab ADD CONSTRAINT fk_6d68cadeb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab ADD CONSTRAINT fk_6d68cade99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.variant_vocab DROP CONSTRAINT fk_bc7f35d7b03a8386');
        $this->addSql('ALTER TABLE vocab.variant_vocab DROP CONSTRAINT fk_bc7f35d799049ece');
        $this->addSql('ALTER TABLE vocab.variant_vocab ADD CONSTRAINT fk_bc7f35d7b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.variant_vocab ADD CONSTRAINT fk_bc7f35d799049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT fk_7255a4e3b03a8386');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT fk_7255a4e399049ece');
        $this->addSql('ALTER TABLE flora.links DROP query');
        $this->addSql('ALTER TABLE flora.links ALTER path SET NOT NULL');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT fk_7255a4e3b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT fk_7255a4e399049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab DROP CONSTRAINT fk_9b076cd1b03a8386');
        $this->addSql('ALTER TABLE vocab.name_type_vocab DROP CONSTRAINT fk_9b076cd199049ece');
        $this->addSql('ALTER TABLE vocab.name_type_vocab ADD CONSTRAINT fk_9b076cd1b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab ADD CONSTRAINT fk_9b076cd199049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT fk_90187b9bb03a8386');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT fk_90187b9b99049ece');
        $this->addSql('ALTER TABLE organization_agents DROP start_date');
        $this->addSql('ALTER TABLE organization_agents DROP end_date');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT fk_90187b9bb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT fk_90187b9b99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.regions DROP CONSTRAINT fk_254516ddb03a8386');
        $this->addSql('ALTER TABLE flora.regions DROP CONSTRAINT fk_254516dd99049ece');
        $this->addSql('ALTER TABLE flora.regions DROP depth');
        $this->addSql('ALTER TABLE flora.regions ADD CONSTRAINT fk_254516ddb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.regions ADD CONSTRAINT fk_254516dd99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT fk_51e44cbbb03a8386');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT fk_51e44cbb99049ece');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT fk_51e44cbbb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT fk_51e44cbb99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab DROP CONSTRAINT fk_ff443d0ab03a8386');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab DROP CONSTRAINT fk_ff443d0a99049ece');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab ADD CONSTRAINT fk_ff443d0ab03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab ADD CONSTRAINT fk_ff443d0a99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab DROP CONSTRAINT fk_95fefe0db03a8386');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab DROP CONSTRAINT fk_95fefe0d99049ece');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab ADD CONSTRAINT fk_95fefe0db03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab ADD CONSTRAINT fk_95fefe0d99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.attributes DROP CONSTRAINT fk_344dc391b03a8386');
        $this->addSql('ALTER TABLE flora.attributes DROP CONSTRAINT fk_344dc39199049ece');
        $this->addSql('ALTER TABLE flora.attributes ADD CONSTRAINT fk_344dc391b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.attributes ADD CONSTRAINT fk_344dc39199049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT fk_cc70fd9b03a8386');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT fk_cc70fd999049ece');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT fk_cc70fd9b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT fk_cc70fd999049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT fk_a242bc35b03a8386');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT fk_a242bc3599049ece');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT fk_a242bc35b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT fk_a242bc3599049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT fk_4e6a844bb03a8386');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT fk_4e6a844b99049ece');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER node_number SET NOT NULL');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER highest_descendant_node_number SET NOT NULL');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER depth TYPE SMALLINT');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER depth DROP DEFAULT');
        $this->addSql('ALTER TABLE flora.taxon_tree ALTER depth SET NOT NULL');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT fk_4e6a844bb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT fk_4e6a844b99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items DROP CONSTRAINT fk_86f092ab03a8386');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items DROP CONSTRAINT fk_86f092a99049ece');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items ADD CONSTRAINT fk_86f092ab03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items ADD CONSTRAINT fk_86f092a99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab DROP CONSTRAINT fk_34242de2b03a8386');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab DROP CONSTRAINT fk_34242de299049ece');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab ADD CONSTRAINT fk_34242de2b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab ADD CONSTRAINT fk_34242de299049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab DROP CONSTRAINT fk_58767f5eb03a8386');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab DROP CONSTRAINT fk_58767f5e99049ece');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab ADD CONSTRAINT fk_58767f5eb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab ADD CONSTRAINT fk_58767f5e99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT fk_4f9e93ecb03a8386');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT fk_4f9e93ec99049ece');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT fk_4f9e93ecb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT fk_4f9e93ec99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatment_versions DROP CONSTRAINT fk_8a89d541b03a8386');
        $this->addSql('ALTER TABLE flora.treatment_versions DROP CONSTRAINT fk_8a89d54199049ece');
        $this->addSql('ALTER TABLE flora.treatment_versions ADD CONSTRAINT fk_8a89d541b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatment_versions ADD CONSTRAINT fk_8a89d54199049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT fk_3a5a6492b03a8386');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT fk_3a5a649299049ece');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT fk_3a5a6492b03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT fk_3a5a649299049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "references" DROP CONSTRAINT fk_9f1e2d9cb03a8386');
        $this->addSql('ALTER TABLE "references" DROP CONSTRAINT fk_9f1e2d9c99049ece');
        $this->addSql('ALTER TABLE "references" ADD CONSTRAINT fk_9f1e2d9cb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "references" ADD CONSTRAINT fk_9f1e2d9c99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents DROP CONSTRAINT fk_9596ab6eb03a8386');
        $this->addSql('ALTER TABLE agents DROP CONSTRAINT fk_9596ab6e99049ece');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT fk_9596ab6eb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT fk_9596ab6e99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT fk_8807a55fb03a8386');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT fk_8807a55f99049ece');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT fk_8807a55fb03a8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT fk_8807a55f99049ece FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
