<?php

namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20171228063242 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA flora');
        $this->addSql('CREATE SCHEMA vocab');
        $this->addSql('CREATE SCHEMA cumulus');
        $this->addSql('CREATE SCHEMA images');
        $this->addSql('CREATE TABLE agents (id SERIAL NOT NULL, agent_type_id INT DEFAULT NULL, user_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(128) NOT NULL, first_name VARCHAR(64) DEFAULT NULL, last_name VARCHAR(64) DEFAULT NULL, initials VARCHAR(32) DEFAULT NULL, legal_name VARCHAR(128) DEFAULT NULL, email VARCHAR(128) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9596AB6E2B6FCFB2 ON agents (guid)');
        $this->addSql('CREATE INDEX IDX_9596AB6E171FEE39 ON agents (agent_type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9596AB6EA76ED395 ON agents (user_id)');
        $this->addSql('CREATE INDEX IDX_9596AB6EB03A8386 ON agents (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9596AB6E99049ECE ON agents (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN agents.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE agent_type (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(64) NOT NULL, uri VARCHAR(64) DEFAULT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2145EDCA2B6FCFB2 ON agent_type (guid)');
        $this->addSql('CREATE INDEX IDX_2145EDCAB03A8386 ON agent_type (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2145EDCA99049ECE ON agent_type (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_2145EDCA5E237E06 ON agent_type (name)');
        $this->addSql('CREATE INDEX IDX_2145EDCA841CB121 ON agent_type (uri)');
        $this->addSql('CREATE INDEX IDX_2145EDCAEA750E8 ON agent_type (label)');
        $this->addSql('COMMENT ON COLUMN agent_type.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.attributes (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(64) NOT NULL, label VARCHAR(64) NOT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_344DC3912B6FCFB2 ON flora.attributes (guid)');
        $this->addSql('CREATE INDEX IDX_344DC391B03A8386 ON flora.attributes (created_by_id)');
        $this->addSql('CREATE INDEX IDX_344DC39199049ECE ON flora.attributes (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_344DC3915E237E06 ON flora.attributes (name)');
        $this->addSql('CREATE INDEX IDX_344DC391EA750E8 ON flora.attributes (label)');
        $this->addSql('COMMENT ON COLUMN flora.attributes.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.changes (id SERIAL NOT NULL, from_taxon_id INT NOT NULL, to_taxon_id INT NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, change_type VARCHAR(64) DEFAULT NULL, is_current BOOLEAN DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A702D7132B6FCFB2 ON flora.changes (guid)');
        $this->addSql('CREATE INDEX IDX_A702D71398FC14EA ON flora.changes (from_taxon_id)');
        $this->addSql('CREATE INDEX IDX_A702D713134A6ADE ON flora.changes (to_taxon_id)');
        $this->addSql('CREATE INDEX IDX_A702D713B03A8386 ON flora.changes (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A702D71399049ECE ON flora.changes (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN flora.changes.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.distribution (id SERIAL NOT NULL, taxon_id INT NOT NULL, region_id INT NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6F7DDB32B6FCFB2 ON flora.distribution (guid)');
        $this->addSql('CREATE INDEX IDX_F6F7DDB3DE13F470 ON flora.distribution (taxon_id)');
        $this->addSql('CREATE INDEX IDX_F6F7DDB398260155 ON flora.distribution (region_id)');
        $this->addSql('CREATE INDEX IDX_F6F7DDB3B03A8386 ON flora.distribution (created_by_id)');
        $this->addSql('CREATE INDEX IDX_F6F7DDB399049ECE ON flora.distribution (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN flora.distribution.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.establishment_means_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_95FEFE0D2B6FCFB2 ON vocab.establishment_means_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_95FEFE0DB03A8386 ON vocab.establishment_means_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_95FEFE0D99049ECE ON vocab.establishment_means_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_95FEFE0D5E237E06 ON vocab.establishment_means_vocab (name)');
        $this->addSql('CREATE INDEX IDX_95FEFE0D841CB121 ON vocab.establishment_means_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_95FEFE0DEA750E8 ON vocab.establishment_means_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.establishment_means_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE group_agents (id SERIAL NOT NULL, member_id INT DEFAULT NULL, group_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, sequence SMALLINT NOT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_461073BE2B6FCFB2 ON group_agents (guid)');
        $this->addSql('CREATE INDEX IDX_461073BE7597D3FE ON group_agents (member_id)');
        $this->addSql('CREATE INDEX IDX_461073BEFE54D947 ON group_agents (group_id)');
        $this->addSql('CREATE INDEX IDX_461073BEB03A8386 ON group_agents (created_by_id)');
        $this->addSql('CREATE INDEX IDX_461073BE99049ECE ON group_agents (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN group_agents.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE cumulus.cumulus_images (id SERIAL NOT NULL, image_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, cumulus_record_id INT DEFAULT NULL, cumulus_catalogue VARCHAR(64) DEFAULT NULL, cumulus_record_name VARCHAR(64) DEFAULT NULL, cumulus_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pixel_x_dimension INT DEFAULT NULL, pixel_y_dimension INT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8D0BC6F2B6FCFB2 ON cumulus.cumulus_images (guid)');
        $this->addSql('CREATE INDEX IDX_E8D0BC6F3DA5256D ON cumulus.cumulus_images (image_id)');
        $this->addSql('CREATE INDEX IDX_E8D0BC6FB03A8386 ON cumulus.cumulus_images (created_by_id)');
        $this->addSql('CREATE INDEX IDX_E8D0BC6F99049ECE ON cumulus.cumulus_images (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_E8D0BC6F248388D2 ON cumulus.cumulus_images (cumulus_catalogue)');
        $this->addSql('CREATE INDEX IDX_E8D0BC6F30D8642B ON cumulus.cumulus_images (cumulus_record_id)');
        $this->addSql('COMMENT ON COLUMN cumulus.cumulus_images.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE images.events (id SERIAL NOT NULL, location_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DB624B932B6FCFB2 ON images.events (guid)');
        $this->addSql('CREATE INDEX IDX_DB624B9364D218E ON images.events (location_id)');
        $this->addSql('CREATE INDEX IDX_DB624B93B03A8386 ON images.events (created_by_id)');
        $this->addSql('CREATE INDEX IDX_DB624B9399049ECE ON images.events (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN images.events.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.feature_vocab (id SERIAL NOT NULL, parent_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, node_number INT DEFAULT NULL, highest_descendant_node_number INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F5ABA0832B6FCFB2 ON vocab.feature_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_F5ABA083727ACA70 ON vocab.feature_vocab (parent_id)');
        $this->addSql('CREATE INDEX IDX_F5ABA083B03A8386 ON vocab.feature_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_F5ABA08399049ECE ON vocab.feature_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_F5ABA0835E237E06 ON vocab.feature_vocab (name)');
        $this->addSql('CREATE INDEX IDX_F5ABA083841CB121 ON vocab.feature_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_F5ABA083EA750E8 ON vocab.feature_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.feature_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE images.identifications (id SERIAL NOT NULL, occurrence_id INT DEFAULT NULL, image_id INT DEFAULT NULL, taxon_id INT NOT NULL, identified_by_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, date_identified DATE DEFAULT NULL, identification_remarks TEXT DEFAULT NULL, is_current BOOLEAN NOT NULL, verbatim_scientific_name VARCHAR(64) DEFAULT NULL, match_type VARCHAR(32) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_553D98C72B6FCFB2 ON images.identifications (guid)');
        $this->addSql('CREATE INDEX IDX_553D98C730572FAC ON images.identifications (occurrence_id)');
        $this->addSql('CREATE INDEX IDX_553D98C73DA5256D ON images.identifications (image_id)');
        $this->addSql('CREATE INDEX IDX_553D98C7DE13F470 ON images.identifications (taxon_id)');
        $this->addSql('CREATE INDEX IDX_553D98C76AAB25CA ON images.identifications (identified_by_id)');
        $this->addSql('CREATE INDEX IDX_553D98C7B03A8386 ON images.identifications (created_by_id)');
        $this->addSql('CREATE INDEX IDX_553D98C799049ECE ON images.identifications (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_553D98C7CACFB2C3 ON images.identifications (is_current)');
        $this->addSql('COMMENT ON COLUMN images.identifications.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE images.images (id SERIAL NOT NULL, occurrence_id INT DEFAULT NULL, subtype_id INT NOT NULL, subject_category_id INT NOT NULL, creator_id INT DEFAULT NULL, license_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, dc_type VARCHAR(64) NOT NULL, caption TEXT DEFAULT NULL, subject_part VARCHAR(64) DEFAULT NULL, subject_orientation VARCHAR(255) DEFAULT NULL, create_date DATE DEFAULT NULL, digitization_date DATE DEFAULT NULL, rights TEXT DEFAULT NULL, is_hero_image BOOLEAN DEFAULT NULL, rating SMALLINT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_68FAA2B32B6FCFB2 ON images.images (guid)');
        $this->addSql('CREATE INDEX IDX_68FAA2B330572FAC ON images.images (occurrence_id)');
        $this->addSql('CREATE INDEX IDX_68FAA2B38E2E245C ON images.images (subtype_id)');
        $this->addSql('CREATE INDEX IDX_68FAA2B38A4F45C6 ON images.images (subject_category_id)');
        $this->addSql('CREATE INDEX IDX_68FAA2B361220EA6 ON images.images (creator_id)');
        $this->addSql('CREATE INDEX IDX_68FAA2B3460F904B ON images.images (license_id)');
        $this->addSql('CREATE INDEX IDX_68FAA2B3B03A8386 ON images.images (created_by_id)');
        $this->addSql('CREATE INDEX IDX_68FAA2B399049ECE ON images.images (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN images.images.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE images.image_access_points (id SERIAL NOT NULL, image_id INT NOT NULL, variant_id INT NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, access_uri VARCHAR(128) NOT NULL, format VARCHAR(32) NOT NULL, pixel_x_dimension INT DEFAULT NULL, pixel_y_dimension INT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_15E807F3E45CECF4 ON images.image_access_points (access_uri)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_15E807F32B6FCFB2 ON images.image_access_points (guid)');
        $this->addSql('CREATE INDEX IDX_15E807F33DA5256D ON images.image_access_points (image_id)');
        $this->addSql('CREATE INDEX IDX_15E807F33B69A9AF ON images.image_access_points (variant_id)');
        $this->addSql('CREATE INDEX IDX_15E807F3B03A8386 ON images.image_access_points (created_by_id)');
        $this->addSql('CREATE INDEX IDX_15E807F399049ECE ON images.image_access_points (modified_by_id)');
        $this->addSql('CREATE UNIQUE INDEX image_variant_idx ON images.image_access_points (image_id, variant_id)');
        $this->addSql('COMMENT ON COLUMN images.image_access_points.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE images.image_features (id SERIAL NOT NULL, image_id INT NOT NULL, feature_id INT NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E03B8542B6FCFB2 ON images.image_features (guid)');
        $this->addSql('CREATE INDEX IDX_4E03B8543DA5256D ON images.image_features (image_id)');
        $this->addSql('CREATE INDEX IDX_4E03B85460E4B879 ON images.image_features (feature_id)');
        $this->addSql('CREATE INDEX IDX_4E03B854B03A8386 ON images.image_features (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4E03B85499049ECE ON images.image_features (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN images.image_features.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.license_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B8C104012B6FCFB2 ON vocab.license_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_B8C10401B03A8386 ON vocab.license_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B8C1040199049ECE ON vocab.license_vocab (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN vocab.license_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE images.locations (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, country VARCHAR(64) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, state_province VARCHAR(64) DEFAULT NULL, locality VARCHAR(255) DEFAULT NULL, decimal_longitude NUMERIC(13, 10) DEFAULT NULL, decimal_latitude NUMERIC(13, 10) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3A90F272B6FCFB2 ON images.locations (guid)');
        $this->addSql('CREATE INDEX IDX_A3A90F27B03A8386 ON images.locations (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A3A90F2799049ECE ON images.locations (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN images.locations.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE images.occurrences (id SERIAL NOT NULL, event_id INT DEFAULT NULL, recorded_by_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, catalog_number VARCHAR(32) DEFAULT NULL, record_number VARCHAR(32) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD5D642B2B6FCFB2 ON images.occurrences (guid)');
        $this->addSql('CREATE INDEX IDX_FD5D642B71F7E88B ON images.occurrences (event_id)');
        $this->addSql('CREATE INDEX IDX_FD5D642BD05A957B ON images.occurrences (recorded_by_id)');
        $this->addSql('CREATE INDEX IDX_FD5D642BB03A8386 ON images.occurrences (created_by_id)');
        $this->addSql('CREATE INDEX IDX_FD5D642B99049ECE ON images.occurrences (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN images.occurrences.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.subject_category_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B6466132B6FCFB2 ON vocab.subject_category_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_3B646613B03A8386 ON vocab.subject_category_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_3B64661399049ECE ON vocab.subject_category_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_3B6466135E237E06 ON vocab.subject_category_vocab (name)');
        $this->addSql('CREATE INDEX IDX_3B646613841CB121 ON vocab.subject_category_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_3B646613EA750E8 ON vocab.subject_category_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.subject_category_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.subtype_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D68CADE2B6FCFB2 ON vocab.subtype_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_6D68CADEB03A8386 ON vocab.subtype_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6D68CADE99049ECE ON vocab.subtype_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_6D68CADE5E237E06 ON vocab.subtype_vocab (name)');
        $this->addSql('CREATE INDEX IDX_6D68CADE841CB121 ON vocab.subtype_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_6D68CADEEA750E8 ON vocab.subtype_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.subtype_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.variant_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC7F35D72B6FCFB2 ON vocab.variant_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_BC7F35D7B03A8386 ON vocab.variant_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_BC7F35D799049ECE ON vocab.variant_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_BC7F35D75E237E06 ON vocab.variant_vocab (name)');
        $this->addSql('CREATE INDEX IDX_BC7F35D7841CB121 ON vocab.variant_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_BC7F35D7EA750E8 ON vocab.variant_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.variant_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.links (id SERIAL NOT NULL, taxon_id INT NOT NULL, source_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, base_url VARCHAR(64) NOT NULL, path VARCHAR(255) NOT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7255A4E32B6FCFB2 ON flora.links (guid)');
        $this->addSql('CREATE INDEX IDX_7255A4E3DE13F470 ON flora.links (taxon_id)');
        $this->addSql('CREATE INDEX IDX_7255A4E3953C1C61 ON flora.links (source_id)');
        $this->addSql('CREATE INDEX IDX_7255A4E3B03A8386 ON flora.links (created_by_id)');
        $this->addSql('CREATE INDEX IDX_7255A4E399049ECE ON flora.links (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN flora.links.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.names (id SERIAL NOT NULL, protologue_id INT DEFAULT NULL, name_type_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(96) NOT NULL, full_name VARCHAR(255) NOT NULL, authorship VARCHAR(255) DEFAULT NULL, nomenclatural_note VARCHAR(255) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51E44CBB2B6FCFB2 ON flora.names (guid)');
        $this->addSql('CREATE INDEX IDX_51E44CBB8924EEB2 ON flora.names (protologue_id)');
        $this->addSql('CREATE INDEX IDX_51E44CBBCD27C92D ON flora.names (name_type_id)');
        $this->addSql('CREATE INDEX IDX_51E44CBBB03A8386 ON flora.names (created_by_id)');
        $this->addSql('CREATE INDEX IDX_51E44CBB99049ECE ON flora.names (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_51E44CBB5E237E06 ON flora.names (name)');
        $this->addSql('CREATE INDEX IDX_51E44CBBDBC463C4 ON flora.names (full_name)');
        $this->addSql('CREATE INDEX IDX_51E44CBB561C2652 ON flora.names (authorship)');
        $this->addSql('COMMENT ON COLUMN flora.names.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.name_type_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B076CD12B6FCFB2 ON vocab.name_type_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_9B076CD1B03A8386 ON vocab.name_type_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9B076CD199049ECE ON vocab.name_type_vocab (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN vocab.name_type_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.occurrence_status_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF443D0A2B6FCFB2 ON vocab.occurrence_status_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_FF443D0AB03A8386 ON vocab.occurrence_status_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_FF443D0A99049ECE ON vocab.occurrence_status_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_FF443D0A5E237E06 ON vocab.occurrence_status_vocab (name)');
        $this->addSql('CREATE INDEX IDX_FF443D0A841CB121 ON vocab.occurrence_status_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_FF443D0AEA750E8 ON vocab.occurrence_status_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.occurrence_status_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE organization_agents (id SERIAL NOT NULL, member_id INT DEFAULT NULL, group_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, role VARCHAR(128) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_90187B9B2B6FCFB2 ON organization_agents (guid)');
        $this->addSql('CREATE INDEX IDX_90187B9B7597D3FE ON organization_agents (member_id)');
        $this->addSql('CREATE INDEX IDX_90187B9BFE54D947 ON organization_agents (group_id)');
        $this->addSql('CREATE INDEX IDX_90187B9BB03A8386 ON organization_agents (created_by_id)');
        $this->addSql('CREATE INDEX IDX_90187B9B99049ECE ON organization_agents (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN organization_agents.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE "references" (id SERIAL NOT NULL, parent_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, author VARCHAR(128) DEFAULT NULL, publication_year VARCHAR(16) DEFAULT NULL, title TEXT DEFAULT NULL, journal_or_book VARCHAR(128) DEFAULT NULL, "collation" VARCHAR(128) DEFAULT NULL, series VARCHAR(32) DEFAULT NULL, edition VARCHAR(32) DEFAULT NULL, volume VARCHAR(32) DEFAULT NULL, part VARCHAR(32) DEFAULT NULL, page VARCHAR(32) DEFAULT NULL, publisher VARCHAR(64) DEFAULT NULL, place_of_publication VARCHAR(64) DEFAULT NULL, subject VARCHAR(64) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F1E2D9C2B6FCFB2 ON "references" (guid)');
        $this->addSql('CREATE INDEX IDX_9F1E2D9C727ACA70 ON "references" (parent_id)');
        $this->addSql('CREATE INDEX IDX_9F1E2D9CB03A8386 ON "references" (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9F1E2D9C99049ECE ON "references" (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN "references".guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.regions (id SERIAL NOT NULL, parent_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, full_name VARCHAR(255) DEFAULT NULL, level INT DEFAULT NULL, node_number INT DEFAULT NULL, highest_descendant_node_number INT DEFAULT NULL, geom geometry(MULTIPOLYGON, 4326) DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_254516DD2B6FCFB2 ON flora.regions (guid)');
        $this->addSql('CREATE INDEX IDX_254516DD727ACA70 ON flora.regions (parent_id)');
        $this->addSql('CREATE INDEX IDX_254516DDB03A8386 ON flora.regions (created_by_id)');
        $this->addSql('CREATE INDEX IDX_254516DD99049ECE ON flora.regions (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN flora.regions.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.taxa (id SERIAL NOT NULL, name_id INT NOT NULL, taxon_tree_def_item_id INT NOT NULL, accepted_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, cultivar_group_id INT DEFAULT NULL, basionym_id INT DEFAULT NULL, name_according_to_id INT DEFAULT NULL, taxonomic_status_id INT DEFAULT NULL, occurrence_status_id INT DEFAULT NULL, establishment_means_id INT DEFAULT NULL, threat_status_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, is_endemic BOOLEAN DEFAULT NULL, taxon_remarks TEXT DEFAULT NULL, do_not_index BOOLEAN DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A5A64922B6FCFB2 ON flora.taxa (guid)');
        $this->addSql('CREATE INDEX IDX_3A5A649271179CD6 ON flora.taxa (name_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492E05BC1D2 ON flora.taxa (taxon_tree_def_item_id)');
        $this->addSql('CREATE INDEX IDX_3A5A64923DA54F6E ON flora.taxa (accepted_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492727ACA70 ON flora.taxa (parent_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492AFCD2317 ON flora.taxa (cultivar_group_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492B01E56BF ON flora.taxa (basionym_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492BC64E79B ON flora.taxa (name_according_to_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492F3CFC345 ON flora.taxa (taxonomic_status_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492B81AB750 ON flora.taxa (occurrence_status_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492B91BFCF0 ON flora.taxa (establishment_means_id)');
        $this->addSql('CREATE INDEX IDX_3A5A64924A6BEBCA ON flora.taxa (threat_status_id)');
        $this->addSql('CREATE INDEX IDX_3A5A6492B03A8386 ON flora.taxa (created_by_id)');
        $this->addSql('CREATE INDEX IDX_3A5A649299049ECE ON flora.taxa (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN flora.taxa.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.taxon_attributes (id SERIAL NOT NULL, taxon_id INT NOT NULL, attribute_id INT NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, attribute_value VARCHAR(255) NOT NULL, remarks TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC70FD92B6FCFB2 ON flora.taxon_attributes (guid)');
        $this->addSql('CREATE INDEX IDX_CC70FD9DE13F470 ON flora.taxon_attributes (taxon_id)');
        $this->addSql('CREATE INDEX IDX_CC70FD9B6E62EFA ON flora.taxon_attributes (attribute_id)');
        $this->addSql('CREATE INDEX IDX_CC70FD9B03A8386 ON flora.taxon_attributes (created_by_id)');
        $this->addSql('CREATE INDEX IDX_CC70FD999049ECE ON flora.taxon_attributes (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN flora.taxon_attributes.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.taxonomic_status_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58767F5E2B6FCFB2 ON vocab.taxonomic_status_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_58767F5EB03A8386 ON vocab.taxonomic_status_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_58767F5E99049ECE ON vocab.taxonomic_status_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_58767F5E5E237E06 ON vocab.taxonomic_status_vocab (name)');
        $this->addSql('CREATE INDEX IDX_58767F5E841CB121 ON vocab.taxonomic_status_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_58767F5EEA750E8 ON vocab.taxonomic_status_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.taxonomic_status_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.taxon_references (id SERIAL NOT NULL, taxon_id INT NOT NULL, reference_id INT NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A242BC352B6FCFB2 ON flora.taxon_references (guid)');
        $this->addSql('CREATE INDEX IDX_A242BC35DE13F470 ON flora.taxon_references (taxon_id)');
        $this->addSql('CREATE INDEX IDX_A242BC351645DEA9 ON flora.taxon_references (reference_id)');
        $this->addSql('CREATE INDEX IDX_A242BC35B03A8386 ON flora.taxon_references (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A242BC3599049ECE ON flora.taxon_references (modified_by_id)');
        $this->addSql('COMMENT ON COLUMN flora.taxon_references.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.taxon_tree (id SERIAL NOT NULL, taxon_id INT NOT NULL, parent_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, node_number INT NOT NULL, highest_descendant_node_number INT NOT NULL, depth SMALLINT NOT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E6A844B2B6FCFB2 ON flora.taxon_tree (guid)');
        $this->addSql('CREATE INDEX IDX_4E6A844BDE13F470 ON flora.taxon_tree (taxon_id)');
        $this->addSql('CREATE INDEX IDX_4E6A844B727ACA70 ON flora.taxon_tree (parent_id)');
        $this->addSql('CREATE INDEX IDX_4E6A844BB03A8386 ON flora.taxon_tree (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4E6A844B99049ECE ON flora.taxon_tree (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_4E6A844B22820AF1 ON flora.taxon_tree (node_number)');
        $this->addSql('CREATE INDEX IDX_4E6A844B362F826F ON flora.taxon_tree (highest_descendant_node_number)');
        $this->addSql('COMMENT ON COLUMN flora.taxon_tree.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.taxon_tree_def_items (id SERIAL NOT NULL, parent_item_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(64) NOT NULL, text_before VARCHAR(16) DEFAULT NULL, text_after VARCHAR(16) DEFAULT NULL, full_name_separator VARCHAR(4) DEFAULT NULL, is_enforced BOOLEAN DEFAULT NULL, is_in_full_name BOOLEAN DEFAULT NULL, rank_id SMALLINT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86F092A2B6FCFB2 ON flora.taxon_tree_def_items (guid)');
        $this->addSql('CREATE INDEX IDX_86F092A60272618 ON flora.taxon_tree_def_items (parent_item_id)');
        $this->addSql('CREATE INDEX IDX_86F092AB03A8386 ON flora.taxon_tree_def_items (created_by_id)');
        $this->addSql('CREATE INDEX IDX_86F092A99049ECE ON flora.taxon_tree_def_items (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_86F092A5E237E06 ON flora.taxon_tree_def_items (name)');
        $this->addSql('CREATE INDEX IDX_86F092A7616678F ON flora.taxon_tree_def_items (rank_id)');
        $this->addSql('COMMENT ON COLUMN flora.taxon_tree_def_items.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vocab.threat_status_vocab (id SERIAL NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, name VARCHAR(40) NOT NULL, uri VARCHAR(128) NOT NULL, label VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34242DE22B6FCFB2 ON vocab.threat_status_vocab (guid)');
        $this->addSql('CREATE INDEX IDX_34242DE2B03A8386 ON vocab.threat_status_vocab (created_by_id)');
        $this->addSql('CREATE INDEX IDX_34242DE299049ECE ON vocab.threat_status_vocab (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_34242DE25E237E06 ON vocab.threat_status_vocab (name)');
        $this->addSql('CREATE INDEX IDX_34242DE2841CB121 ON vocab.threat_status_vocab (uri)');
        $this->addSql('CREATE INDEX IDX_34242DE2EA750E8 ON vocab.threat_status_vocab (label)');
        $this->addSql('COMMENT ON COLUMN vocab.threat_status_vocab.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.treatments (id SERIAL NOT NULL, taxon_id INT NOT NULL, accepted_id INT NOT NULL, taxonomic_status_id INT DEFAULT NULL, source_id INT DEFAULT NULL, author_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, is_current_treatment BOOLEAN DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4F9E93ECDE13F470 ON flora.treatments (taxon_id)');
        $this->addSql('CREATE INDEX IDX_4F9E93EC3DA54F6E ON flora.treatments (accepted_id)');
        $this->addSql('CREATE INDEX IDX_4F9E93ECF3CFC345 ON flora.treatments (taxonomic_status_id)');
        $this->addSql('CREATE INDEX IDX_4F9E93EC953C1C61 ON flora.treatments (source_id)');
        $this->addSql('CREATE INDEX IDX_4F9E93ECF675F31B ON flora.treatments (author_id)');
        $this->addSql('CREATE INDEX IDX_4F9E93ECB03A8386 ON flora.treatments (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4F9E93EC99049ECE ON flora.treatments (modified_by_id)');
        $this->addSql('CREATE UNIQUE INDEX treatment_guid_idx ON flora.treatments (guid)');
        $this->addSql('COMMENT ON COLUMN flora.treatments.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.treatment_versions (id SERIAL NOT NULL, treatment_id INT NOT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, html TEXT NOT NULL, is_current_version BOOLEAN DEFAULT NULL, is_updated BOOLEAN DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A89D5412B6FCFB2 ON flora.treatment_versions (guid)');
        $this->addSql('CREATE INDEX IDX_8A89D541471C0366 ON flora.treatment_versions (treatment_id)');
        $this->addSql('CREATE INDEX IDX_8A89D541B03A8386 ON flora.treatment_versions (created_by_id)');
        $this->addSql('CREATE INDEX IDX_8A89D54199049ECE ON flora.treatment_versions (modified_by_id)');
        $this->addSql('CREATE UNIQUE INDEX treatment_version_idx ON flora.treatment_versions (treatment_id, version)');
        $this->addSql('COMMENT ON COLUMN flora.treatment_versions.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE flora.vernacular_names (id SERIAL NOT NULL, taxon_id INT NOT NULL, source_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, modified_by_id INT DEFAULT NULL, vernacular_name VARCHAR(64) NOT NULL, is_preferred_name BOOLEAN DEFAULT NULL, vernacular_name_usage VARCHAR(64) DEFAULT NULL, language VARCHAR(2) DEFAULT NULL, organism_part VARCHAR(64) DEFAULT NULL, taxon_remarks TEXT DEFAULT NULL, timestamp_created TIMESTAMP(0) WITH TIME ZONE NOT NULL, timestamp_modified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, guid UUID DEFAULT NULL, version SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8807A55F2B6FCFB2 ON flora.vernacular_names (guid)');
        $this->addSql('CREATE INDEX IDX_8807A55FDE13F470 ON flora.vernacular_names (taxon_id)');
        $this->addSql('CREATE INDEX IDX_8807A55F953C1C61 ON flora.vernacular_names (source_id)');
        $this->addSql('CREATE INDEX IDX_8807A55FB03A8386 ON flora.vernacular_names (created_by_id)');
        $this->addSql('CREATE INDEX IDX_8807A55F99049ECE ON flora.vernacular_names (modified_by_id)');
        $this->addSql('CREATE INDEX IDX_8807A55FD8354D5A ON flora.vernacular_names (vernacular_name)');
        $this->addSql('CREATE INDEX IDX_8807A55F47755A47 ON flora.vernacular_names (is_preferred_name)');
        $this->addSql('COMMENT ON COLUMN flora.vernacular_names.guid IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT FK_9596AB6E171FEE39 FOREIGN KEY (agent_type_id) REFERENCES agent_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT FK_9596AB6EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT FK_9596AB6EB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents ADD CONSTRAINT FK_9596AB6E99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_type ADD CONSTRAINT FK_2145EDCAB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_type ADD CONSTRAINT FK_2145EDCA99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.attributes ADD CONSTRAINT FK_344DC391B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.attributes ADD CONSTRAINT FK_344DC39199049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT FK_A702D71398FC14EA FOREIGN KEY (from_taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT FK_A702D713134A6ADE FOREIGN KEY (to_taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT FK_A702D713B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.changes ADD CONSTRAINT FK_A702D71399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT FK_F6F7DDB3DE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT FK_F6F7DDB398260155 FOREIGN KEY (region_id) REFERENCES flora.regions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT FK_F6F7DDB3B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.distribution ADD CONSTRAINT FK_F6F7DDB399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab ADD CONSTRAINT FK_95FEFE0DB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab ADD CONSTRAINT FK_95FEFE0D99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT FK_461073BE7597D3FE FOREIGN KEY (member_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT FK_461073BEFE54D947 FOREIGN KEY (group_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT FK_461073BEB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_agents ADD CONSTRAINT FK_461073BE99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images ADD CONSTRAINT FK_E8D0BC6F3DA5256D FOREIGN KEY (image_id) REFERENCES images.images (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images ADD CONSTRAINT FK_E8D0BC6FB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images ADD CONSTRAINT FK_E8D0BC6F99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.events ADD CONSTRAINT FK_DB624B9364D218E FOREIGN KEY (location_id) REFERENCES images.locations (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.events ADD CONSTRAINT FK_DB624B93B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.events ADD CONSTRAINT FK_DB624B9399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.feature_vocab ADD CONSTRAINT FK_F5ABA083727ACA70 FOREIGN KEY (parent_id) REFERENCES vocab.feature_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.feature_vocab ADD CONSTRAINT FK_F5ABA083B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.feature_vocab ADD CONSTRAINT FK_F5ABA08399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C730572FAC FOREIGN KEY (occurrence_id) REFERENCES images.occurrences (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C73DA5256D FOREIGN KEY (image_id) REFERENCES images.images (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C7DE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C76AAB25CA FOREIGN KEY (identified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C7B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.identifications ADD CONSTRAINT FK_553D98C799049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B330572FAC FOREIGN KEY (occurrence_id) REFERENCES images.occurrences (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B38E2E245C FOREIGN KEY (subtype_id) REFERENCES vocab.subtype_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B38A4F45C6 FOREIGN KEY (subject_category_id) REFERENCES vocab.subject_category_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B361220EA6 FOREIGN KEY (creator_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B3460F904B FOREIGN KEY (license_id) REFERENCES vocab.license_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B3B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.images ADD CONSTRAINT FK_68FAA2B399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT FK_15E807F33DA5256D FOREIGN KEY (image_id) REFERENCES images.images (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT FK_15E807F33B69A9AF FOREIGN KEY (variant_id) REFERENCES vocab.variant_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT FK_15E807F3B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_access_points ADD CONSTRAINT FK_15E807F399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT FK_4E03B8543DA5256D FOREIGN KEY (image_id) REFERENCES images.images (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT FK_4E03B85460E4B879 FOREIGN KEY (feature_id) REFERENCES vocab.feature_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT FK_4E03B854B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.image_features ADD CONSTRAINT FK_4E03B85499049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.license_vocab ADD CONSTRAINT FK_B8C10401B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.license_vocab ADD CONSTRAINT FK_B8C1040199049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.locations ADD CONSTRAINT FK_A3A90F27B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.locations ADD CONSTRAINT FK_A3A90F2799049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT FK_FD5D642B71F7E88B FOREIGN KEY (event_id) REFERENCES images.events (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT FK_FD5D642BD05A957B FOREIGN KEY (recorded_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT FK_FD5D642BB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE images.occurrences ADD CONSTRAINT FK_FD5D642B99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab ADD CONSTRAINT FK_3B646613B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab ADD CONSTRAINT FK_3B64661399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab ADD CONSTRAINT FK_6D68CADEB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab ADD CONSTRAINT FK_6D68CADE99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.variant_vocab ADD CONSTRAINT FK_BC7F35D7B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.variant_vocab ADD CONSTRAINT FK_BC7F35D799049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT FK_7255A4E3DE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT FK_7255A4E3953C1C61 FOREIGN KEY (source_id) REFERENCES "references" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT FK_7255A4E3B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.links ADD CONSTRAINT FK_7255A4E399049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT FK_51E44CBB8924EEB2 FOREIGN KEY (protologue_id) REFERENCES "references" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT FK_51E44CBBCD27C92D FOREIGN KEY (name_type_id) REFERENCES vocab.name_type_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT FK_51E44CBBB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.names ADD CONSTRAINT FK_51E44CBB99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab ADD CONSTRAINT FK_9B076CD1B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab ADD CONSTRAINT FK_9B076CD199049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab ADD CONSTRAINT FK_FF443D0AB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab ADD CONSTRAINT FK_FF443D0A99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT FK_90187B9B7597D3FE FOREIGN KEY (member_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT FK_90187B9BFE54D947 FOREIGN KEY (group_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT FK_90187B9BB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_agents ADD CONSTRAINT FK_90187B9B99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "references" ADD CONSTRAINT FK_9F1E2D9C727ACA70 FOREIGN KEY (parent_id) REFERENCES "references" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "references" ADD CONSTRAINT FK_9F1E2D9CB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "references" ADD CONSTRAINT FK_9F1E2D9C99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.regions ADD CONSTRAINT FK_254516DD727ACA70 FOREIGN KEY (parent_id) REFERENCES flora.regions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.regions ADD CONSTRAINT FK_254516DDB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.regions ADD CONSTRAINT FK_254516DD99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A649271179CD6 FOREIGN KEY (name_id) REFERENCES flora.names (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492E05BC1D2 FOREIGN KEY (taxon_tree_def_item_id) REFERENCES flora.taxon_tree_def_items (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A64923DA54F6E FOREIGN KEY (accepted_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492727ACA70 FOREIGN KEY (parent_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492AFCD2317 FOREIGN KEY (cultivar_group_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492B01E56BF FOREIGN KEY (basionym_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492BC64E79B FOREIGN KEY (name_according_to_id) REFERENCES "references" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492F3CFC345 FOREIGN KEY (taxonomic_status_id) REFERENCES vocab.taxonomic_status_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492B81AB750 FOREIGN KEY (occurrence_status_id) REFERENCES vocab.occurrence_status_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492B91BFCF0 FOREIGN KEY (establishment_means_id) REFERENCES vocab.establishment_means_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A64924A6BEBCA FOREIGN KEY (threat_status_id) REFERENCES vocab.threat_status_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A6492B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxa ADD CONSTRAINT FK_3A5A649299049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT FK_CC70FD9DE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT FK_CC70FD9B6E62EFA FOREIGN KEY (attribute_id) REFERENCES flora.attributes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT FK_CC70FD9B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_attributes ADD CONSTRAINT FK_CC70FD999049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab ADD CONSTRAINT FK_58767F5EB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab ADD CONSTRAINT FK_58767F5E99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT FK_A242BC35DE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT FK_A242BC351645DEA9 FOREIGN KEY (reference_id) REFERENCES "references" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT FK_A242BC35B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_references ADD CONSTRAINT FK_A242BC3599049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT FK_4E6A844BDE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT FK_4E6A844B727ACA70 FOREIGN KEY (parent_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT FK_4E6A844BB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree ADD CONSTRAINT FK_4E6A844B99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items ADD CONSTRAINT FK_86F092A60272618 FOREIGN KEY (parent_item_id) REFERENCES flora.taxon_tree_def_items (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items ADD CONSTRAINT FK_86F092AB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items ADD CONSTRAINT FK_86F092A99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab ADD CONSTRAINT FK_34242DE2B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab ADD CONSTRAINT FK_34242DE299049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93ECDE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93EC3DA54F6E FOREIGN KEY (accepted_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93ECF3CFC345 FOREIGN KEY (taxonomic_status_id) REFERENCES vocab.taxonomic_status_vocab (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93EC953C1C61 FOREIGN KEY (source_id) REFERENCES "references" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93ECF675F31B FOREIGN KEY (author_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93ECB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatments ADD CONSTRAINT FK_4F9E93EC99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatment_versions ADD CONSTRAINT FK_8A89D541471C0366 FOREIGN KEY (treatment_id) REFERENCES flora.treatments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatment_versions ADD CONSTRAINT FK_8A89D541B03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.treatment_versions ADD CONSTRAINT FK_8A89D54199049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT FK_8807A55FDE13F470 FOREIGN KEY (taxon_id) REFERENCES flora.taxa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT FK_8807A55F953C1C61 FOREIGN KEY (source_id) REFERENCES "references" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT FK_8807A55FB03A8386 FOREIGN KEY (created_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE flora.vernacular_names ADD CONSTRAINT FK_8807A55F99049ECE FOREIGN KEY (modified_by_id) REFERENCES agents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE agents DROP CONSTRAINT FK_9596AB6EB03A8386');
        $this->addSql('ALTER TABLE agents DROP CONSTRAINT FK_9596AB6E99049ECE');
        $this->addSql('ALTER TABLE agent_type DROP CONSTRAINT FK_2145EDCAB03A8386');
        $this->addSql('ALTER TABLE agent_type DROP CONSTRAINT FK_2145EDCA99049ECE');
        $this->addSql('ALTER TABLE flora.attributes DROP CONSTRAINT FK_344DC391B03A8386');
        $this->addSql('ALTER TABLE flora.attributes DROP CONSTRAINT FK_344DC39199049ECE');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT FK_A702D713B03A8386');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT FK_A702D71399049ECE');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT FK_F6F7DDB3B03A8386');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT FK_F6F7DDB399049ECE');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab DROP CONSTRAINT FK_95FEFE0DB03A8386');
        $this->addSql('ALTER TABLE vocab.establishment_means_vocab DROP CONSTRAINT FK_95FEFE0D99049ECE');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT FK_461073BE7597D3FE');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT FK_461073BEFE54D947');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT FK_461073BEB03A8386');
        $this->addSql('ALTER TABLE group_agents DROP CONSTRAINT FK_461073BE99049ECE');
        $this->addSql('ALTER TABLE cumulus.cumulus_images DROP CONSTRAINT FK_E8D0BC6FB03A8386');
        $this->addSql('ALTER TABLE cumulus.cumulus_images DROP CONSTRAINT FK_E8D0BC6F99049ECE');
        $this->addSql('ALTER TABLE images.events DROP CONSTRAINT FK_DB624B93B03A8386');
        $this->addSql('ALTER TABLE images.events DROP CONSTRAINT FK_DB624B9399049ECE');
        $this->addSql('ALTER TABLE vocab.feature_vocab DROP CONSTRAINT FK_F5ABA083B03A8386');
        $this->addSql('ALTER TABLE vocab.feature_vocab DROP CONSTRAINT FK_F5ABA08399049ECE');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C76AAB25CA');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C7B03A8386');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C799049ECE');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B361220EA6');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B3B03A8386');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B399049ECE');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT FK_15E807F3B03A8386');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT FK_15E807F399049ECE');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT FK_4E03B854B03A8386');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT FK_4E03B85499049ECE');
        $this->addSql('ALTER TABLE vocab.license_vocab DROP CONSTRAINT FK_B8C10401B03A8386');
        $this->addSql('ALTER TABLE vocab.license_vocab DROP CONSTRAINT FK_B8C1040199049ECE');
        $this->addSql('ALTER TABLE images.locations DROP CONSTRAINT FK_A3A90F27B03A8386');
        $this->addSql('ALTER TABLE images.locations DROP CONSTRAINT FK_A3A90F2799049ECE');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT FK_FD5D642BD05A957B');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT FK_FD5D642BB03A8386');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT FK_FD5D642B99049ECE');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab DROP CONSTRAINT FK_3B646613B03A8386');
        $this->addSql('ALTER TABLE vocab.subject_category_vocab DROP CONSTRAINT FK_3B64661399049ECE');
        $this->addSql('ALTER TABLE vocab.subtype_vocab DROP CONSTRAINT FK_6D68CADEB03A8386');
        $this->addSql('ALTER TABLE vocab.subtype_vocab DROP CONSTRAINT FK_6D68CADE99049ECE');
        $this->addSql('ALTER TABLE vocab.variant_vocab DROP CONSTRAINT FK_BC7F35D7B03A8386');
        $this->addSql('ALTER TABLE vocab.variant_vocab DROP CONSTRAINT FK_BC7F35D799049ECE');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT FK_7255A4E3B03A8386');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT FK_7255A4E399049ECE');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT FK_51E44CBBB03A8386');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT FK_51E44CBB99049ECE');
        $this->addSql('ALTER TABLE vocab.name_type_vocab DROP CONSTRAINT FK_9B076CD1B03A8386');
        $this->addSql('ALTER TABLE vocab.name_type_vocab DROP CONSTRAINT FK_9B076CD199049ECE');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab DROP CONSTRAINT FK_FF443D0AB03A8386');
        $this->addSql('ALTER TABLE vocab.occurrence_status_vocab DROP CONSTRAINT FK_FF443D0A99049ECE');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT FK_90187B9B7597D3FE');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT FK_90187B9BFE54D947');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT FK_90187B9BB03A8386');
        $this->addSql('ALTER TABLE organization_agents DROP CONSTRAINT FK_90187B9B99049ECE');
        $this->addSql('ALTER TABLE "references" DROP CONSTRAINT FK_9F1E2D9CB03A8386');
        $this->addSql('ALTER TABLE "references" DROP CONSTRAINT FK_9F1E2D9C99049ECE');
        $this->addSql('ALTER TABLE flora.regions DROP CONSTRAINT FK_254516DDB03A8386');
        $this->addSql('ALTER TABLE flora.regions DROP CONSTRAINT FK_254516DD99049ECE');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492B03A8386');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A649299049ECE');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT FK_CC70FD9B03A8386');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT FK_CC70FD999049ECE');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab DROP CONSTRAINT FK_58767F5EB03A8386');
        $this->addSql('ALTER TABLE vocab.taxonomic_status_vocab DROP CONSTRAINT FK_58767F5E99049ECE');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT FK_A242BC35B03A8386');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT FK_A242BC3599049ECE');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT FK_4E6A844BB03A8386');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT FK_4E6A844B99049ECE');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items DROP CONSTRAINT FK_86F092AB03A8386');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items DROP CONSTRAINT FK_86F092A99049ECE');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab DROP CONSTRAINT FK_34242DE2B03A8386');
        $this->addSql('ALTER TABLE vocab.threat_status_vocab DROP CONSTRAINT FK_34242DE299049ECE');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93ECF675F31B');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93ECB03A8386');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93EC99049ECE');
        $this->addSql('ALTER TABLE flora.treatment_versions DROP CONSTRAINT FK_8A89D541B03A8386');
        $this->addSql('ALTER TABLE flora.treatment_versions DROP CONSTRAINT FK_8A89D54199049ECE');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT FK_8807A55FB03A8386');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT FK_8807A55F99049ECE');
        $this->addSql('ALTER TABLE agents DROP CONSTRAINT FK_9596AB6E171FEE39');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT FK_CC70FD9B6E62EFA');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492B91BFCF0');
        $this->addSql('ALTER TABLE images.occurrences DROP CONSTRAINT FK_FD5D642B71F7E88B');
        $this->addSql('ALTER TABLE vocab.feature_vocab DROP CONSTRAINT FK_F5ABA083727ACA70');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT FK_4E03B85460E4B879');
        $this->addSql('ALTER TABLE cumulus.cumulus_images DROP CONSTRAINT FK_E8D0BC6F3DA5256D');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C73DA5256D');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT FK_15E807F33DA5256D');
        $this->addSql('ALTER TABLE images.image_features DROP CONSTRAINT FK_4E03B8543DA5256D');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B3460F904B');
        $this->addSql('ALTER TABLE images.events DROP CONSTRAINT FK_DB624B9364D218E');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C730572FAC');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B330572FAC');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B38A4F45C6');
        $this->addSql('ALTER TABLE images.images DROP CONSTRAINT FK_68FAA2B38E2E245C');
        $this->addSql('ALTER TABLE images.image_access_points DROP CONSTRAINT FK_15E807F33B69A9AF');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A649271179CD6');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT FK_51E44CBBCD27C92D');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492B81AB750');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT FK_7255A4E3953C1C61');
        $this->addSql('ALTER TABLE flora.names DROP CONSTRAINT FK_51E44CBB8924EEB2');
        $this->addSql('ALTER TABLE "references" DROP CONSTRAINT FK_9F1E2D9C727ACA70');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492BC64E79B');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT FK_A242BC351645DEA9');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93EC953C1C61');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT FK_8807A55F953C1C61');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT FK_F6F7DDB398260155');
        $this->addSql('ALTER TABLE flora.regions DROP CONSTRAINT FK_254516DD727ACA70');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT FK_A702D71398FC14EA');
        $this->addSql('ALTER TABLE flora.changes DROP CONSTRAINT FK_A702D713134A6ADE');
        $this->addSql('ALTER TABLE flora.distribution DROP CONSTRAINT FK_F6F7DDB3DE13F470');
        $this->addSql('ALTER TABLE images.identifications DROP CONSTRAINT FK_553D98C7DE13F470');
        $this->addSql('ALTER TABLE flora.links DROP CONSTRAINT FK_7255A4E3DE13F470');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A64923DA54F6E');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492727ACA70');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492AFCD2317');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492B01E56BF');
        $this->addSql('ALTER TABLE flora.taxon_attributes DROP CONSTRAINT FK_CC70FD9DE13F470');
        $this->addSql('ALTER TABLE flora.taxon_references DROP CONSTRAINT FK_A242BC35DE13F470');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT FK_4E6A844BDE13F470');
        $this->addSql('ALTER TABLE flora.taxon_tree DROP CONSTRAINT FK_4E6A844B727ACA70');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93ECDE13F470');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93EC3DA54F6E');
        $this->addSql('ALTER TABLE flora.vernacular_names DROP CONSTRAINT FK_8807A55FDE13F470');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492F3CFC345');
        $this->addSql('ALTER TABLE flora.treatments DROP CONSTRAINT FK_4F9E93ECF3CFC345');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A6492E05BC1D2');
        $this->addSql('ALTER TABLE flora.taxon_tree_def_items DROP CONSTRAINT FK_86F092A60272618');
        $this->addSql('ALTER TABLE flora.taxa DROP CONSTRAINT FK_3A5A64924A6BEBCA');
        $this->addSql('ALTER TABLE flora.treatment_versions DROP CONSTRAINT FK_8A89D541471C0366');
        $this->addSql('DROP TABLE agents');
        $this->addSql('DROP TABLE agent_type');
        $this->addSql('DROP TABLE flora.attributes');
        $this->addSql('DROP TABLE flora.changes');
        $this->addSql('DROP TABLE flora.distribution');
        $this->addSql('DROP TABLE vocab.establishment_means_vocab');
        $this->addSql('DROP TABLE group_agents');
        $this->addSql('DROP TABLE cumulus.cumulus_images');
        $this->addSql('DROP TABLE images.events');
        $this->addSql('DROP TABLE vocab.feature_vocab');
        $this->addSql('DROP TABLE images.identifications');
        $this->addSql('DROP TABLE images.images');
        $this->addSql('DROP TABLE images.image_access_points');
        $this->addSql('DROP TABLE images.image_features');
        $this->addSql('DROP TABLE vocab.license_vocab');
        $this->addSql('DROP TABLE images.locations');
        $this->addSql('DROP TABLE images.occurrences');
        $this->addSql('DROP TABLE vocab.subject_category_vocab');
        $this->addSql('DROP TABLE vocab.subtype_vocab');
        $this->addSql('DROP TABLE vocab.variant_vocab');
        $this->addSql('DROP TABLE flora.links');
        $this->addSql('DROP TABLE flora.names');
        $this->addSql('DROP TABLE vocab.name_type_vocab');
        $this->addSql('DROP TABLE vocab.occurrence_status_vocab');
        $this->addSql('DROP TABLE organization_agents');
        $this->addSql('DROP TABLE "references"');
        $this->addSql('DROP TABLE flora.regions');
        $this->addSql('DROP TABLE flora.taxa');
        $this->addSql('DROP TABLE flora.taxon_attributes');
        $this->addSql('DROP TABLE vocab.taxonomic_status_vocab');
        $this->addSql('DROP TABLE flora.taxon_references');
        $this->addSql('DROP TABLE flora.taxon_tree');
        $this->addSql('DROP TABLE flora.taxon_tree_def_items');
        $this->addSql('DROP TABLE vocab.threat_status_vocab');
        $this->addSql('DROP TABLE flora.treatments');
        $this->addSql('DROP TABLE flora.treatment_versions');
        $this->addSql('DROP TABLE flora.vernacular_names');
    }
}
